/*
-- Query: SELECT * FROM variables
LIMIT 0, 1000

-- Date: 2018-09-10 17:20
*/
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (1,'Temperature in Celsius','C','T',1,'T');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (2,'Fat','%','Fat',1,'Fat');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (3,'Water','%','Water content',1,'H2O');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (4,'Protein','%','Protein',1,'Protein');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (5,'Carbohydrates','%','Carbs',1,'Carbs');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (6,'Density','kg/m^3','ρ',0,'ρ');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (7,'Thermal Conductivity','W/m K','Thermal Conductivity',0,'k');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (8,'Frequency','Hz','Frequency',1,'f');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (9,'Porosity','Fraction','Ratio of total volume occupied by fluid to the total volume of bulk solid',0,'ϵ');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (10,'Sodium','%','salt content, fraction',1,'Na');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (11,'Air','Fraction','',1,'A');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (12,'Ice','Fraction','',0,'Ice');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (203,'Protein''','g',NULL,1,'PROCNT');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (204,'Total lipid (fat)','g','',1,'LipFAT');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (205,'Carbohydrate, by difference','g',NULL,1,'CHOCDF');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (207,'Ash','g',NULL,1,'ASH');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (208,'Energy','kcal',NULL,1,'ENERC_KCAL');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (209,'Starch','g',NULL,1,'STARCH');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (210,'Sucrose','g',NULL,1,'SUCS');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (211,'Glucose (dextrose)','g',NULL,1,'GLUS');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (212,'Fructose','g',NULL,1,'FRUS');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (213,'Lactose','g',NULL,1,'LACS');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (214,'Maltose','g',NULL,1,'MALS');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (221,'Alcohol, ethyl','g',NULL,1,'ALC');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (255,'Water','g',NULL,1,'WATER');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (257,'Adjusted Protein','g',NULL,1,'');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (262,'Caffeine','mg',NULL,1,'CAFFN');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (263,'Theobromine','mg',NULL,1,'THEBRN');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (268,'Energy','kJ',NULL,1,'ENERC_KJ');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (269,'Sugars, total','g',NULL,1,'SUGAR');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (287,'Galactose','g',NULL,1,'GALS');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (291,'Fiber','g','Total Dietary Fiber',1,'FIBTG');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (301,'Calcium, Ca','mg',NULL,1,'CA');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (303,'Iron, Fe','mg',NULL,1,'FE');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (304,'Magnesium, Mg','mg',NULL,1,'MG');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (305,'Phosphorus, P','mg',NULL,1,'P');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (306,'Potassium, K','mg','',1,'K_pot');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (307,'Sodium, Na','mg','',1,'Sodium');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (309,'Zinc, Zn','mg',NULL,1,'ZN');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (312,'Copper, Cu','mg',NULL,1,'CU');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (313,'Fluoride, F','µg',NULL,1,'FLD');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (315,'Manganese, Mn','mg',NULL,1,'MN');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (317,'Selenium, Se','µg',NULL,1,'SE');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (318,'Vitamin A, IU','IU',NULL,1,'VITA_IU');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (319,'Retinol','µg',NULL,1,'RETOL');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (320,'Vitamin A, RAE','µg',NULL,1,'VITA_RAE');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (321,'Carotene, beta','µg',NULL,1,'CARTB');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (322,'Carotene, alpha','µg',NULL,1,'CARTA');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (323,'Vitamin E (alpha-tocopherol)','mg',NULL,1,'TOCPHA');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (324,'Vitamin D','IU',NULL,1,'VITD');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (325,'Vitamin D2 (ergocalciferol)','µg',NULL,1,'ERGCAL');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (326,'Vitamin D3 (cholecalciferol)','µg',NULL,1,'CHOCAL');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (328,'Vitamin D (D2 + D3)','µg',NULL,1,'VITD');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (334,'Cryptoxanthin, beta','µg',NULL,1,'CRYPX');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (337,'Lycopene','µg',NULL,1,'LYCPN');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (338,'Lutein + zeaxanthin','µg',NULL,1,'LUT+ZEA');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (341,'Tocopherol, beta','mg',NULL,1,'TOCPHB');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (342,'Tocopherol, gamma','mg',NULL,1,'TOCPHG');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (343,'Tocopherol, delta','mg',NULL,1,'TOCPHD');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (344,'Tocotrienol, alpha','mg',NULL,1,'TOCTRA');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (345,'Tocotrienol, beta','mg',NULL,1,'TOCTRB');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (346,'Tocotrienol, gamma','mg',NULL,1,'TOCTRG');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (347,'Tocotrienol, delta','mg',NULL,1,'TOCTRD');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (401,'Vitamin C, total ascorbic acid','mg',NULL,1,'VITC');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (404,'Thiamin','mg',NULL,1,'THIA');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (405,'Riboflavin','mg',NULL,1,'RIBF');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (406,'Niacin','mg',NULL,1,'NIA');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (410,'Pantothenic acid','mg',NULL,1,'PANTAC');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (415,'Vitamin B-6','mg',NULL,1,'VITB6A');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (417,'Folate, total','µg',NULL,1,'FOL');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (418,'Vitamin B-12','µg',NULL,1,'VITB12');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (421,'Choline, total','mg',NULL,1,'CHOLN');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (428,'Menaquinone-4','µg',NULL,1,'MK4');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (429,'Dihydrophylloquinone','µg',NULL,1,'VITK1D');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (430,'Vitamin K (phylloquinone)','µg',NULL,1,'VITK1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (431,'Folic acid','µg',NULL,1,'FOLAC');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (432,'Folate, food','µg',NULL,1,'FOLFD');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (435,'Folate, DFE','µg',NULL,1,'FOLDFE');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (454,'Betaine','mg',NULL,1,'BETN');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (501,'Tryptophan','g',NULL,1,'TRP_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (502,'Threonine','g',NULL,1,'THR_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (503,'Isoleucine','g',NULL,1,'ILE_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (504,'Leucine','g',NULL,1,'LEU_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (505,'Lysine','g',NULL,1,'LYS_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (506,'Methionine','g',NULL,1,'MET_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (507,'Cystine','g',NULL,1,'CYS_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (508,'Phenylalanine','g',NULL,1,'PHE_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (509,'Tyrosine','g',NULL,1,'TYR_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (510,'Valine','g',NULL,1,'VAL_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (511,'Arginine','g',NULL,1,'ARG_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (512,'Histidine','g',NULL,1,'HISTN_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (513,'Alanine','g',NULL,1,'ALA_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (514,'Aspartic acid','g',NULL,1,'ASP_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (515,'Glutamic acid','g',NULL,1,'GLU_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (516,'Glycine','g',NULL,1,'GLY_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (517,'Proline','g',NULL,1,'PRO_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (518,'Serine','g',NULL,1,'SER_G');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (521,'Hydroxyproline','g',NULL,1,'HYP');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (573,'Vitamin E, added','mg',NULL,1,'');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (578,'Vitamin B-12, added','µg',NULL,1,'');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (601,'Cholesterol','mg',NULL,1,'CHOLE');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (605,'Fatty acids, total trans','g',NULL,1,'FATRN');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (606,'Fatty acids, total saturated','g',NULL,1,'FASAT');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (607,'4:0','g',NULL,1,'F4D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (608,'6:0','g',NULL,1,'F6D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (609,'8:0','g',NULL,1,'F8D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (610,'10:0','g',NULL,1,'F10D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (611,'12:0','g',NULL,1,'F12D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (612,'14:0','g',NULL,1,'F14D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (613,'16:0','g',NULL,1,'F16D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (614,'18:0','g',NULL,1,'F18D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (615,'20:0','g',NULL,1,'F20D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (617,'18:1 undifferentiated','g',NULL,1,'F18D1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (618,'18:2 undifferentiated','g',NULL,1,'F18D2');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (619,'18:3 undifferentiated','g',NULL,1,'F18D3');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (620,'20:4 undifferentiated','g',NULL,1,'F20D4');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (621,'22:6 n-3 (DHA)','g',NULL,1,'F22D6');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (624,'22:0','g',NULL,1,'F22D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (625,'14:1','g',NULL,1,'F14D1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (626,'16:1 undifferentiated','g',NULL,1,'F16D1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (627,'18:4','g',NULL,1,'F18D4');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (628,'20:1','g',NULL,1,'F20D1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (629,'20:5 n-3 (EPA)','g',NULL,1,'F20D5');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (630,'22:1 undifferentiated','g',NULL,1,'F22D1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (631,'22:5 n-3 (DPA)','g',NULL,1,'F22D5');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (636,'Phytosterols','mg',NULL,1,'PHYSTR');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (638,'Stigmasterol','mg',NULL,1,'STID7');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (639,'Campesterol','mg',NULL,1,'CAMD5');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (641,'Beta-sitosterol','mg',NULL,1,'SITSTR');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (645,'Fatty acids, total monounsaturated','g',NULL,1,'FAMS');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (646,'Fatty acids, total polyunsaturated','g',NULL,1,'FAPU');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (652,'15:0','g',NULL,1,'F15D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (653,'17:0','g',NULL,1,'F17D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (654,'24:0','g',NULL,1,'F24D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (662,'16:1 t','g',NULL,1,'F16D1T');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (663,'18:1 t','g',NULL,1,'F18D1T');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (664,'22:1 t','g',NULL,1,'F22D1T');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (665,'18:2 t not further defined','g',NULL,1,'');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (666,'18:2 i','g',NULL,1,'');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (669,'18:2 t,t','g',NULL,1,'F18D2TT');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (670,'18:2 CLAs','g',NULL,1,'F18D2CLA');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (671,'24:1 c','g',NULL,1,'F24D1C');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (672,'20:2 n-6 c,c','g',NULL,1,'F20D2CN6');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (673,'16:1 c','g',NULL,1,'F16D1C');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (674,'18:1 c','g',NULL,1,'F18D1C');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (675,'18:2 n-6 c,c','g',NULL,1,'F18D2CN6');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (676,'22:1 c','g',NULL,1,'F22D1C');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (685,'18:3 n-6 c,c,c','g',NULL,1,'F18D3CN6');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (687,'17:1','g',NULL,1,'F17D1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (689,'20:3 undifferentiated','g',NULL,1,'F20D3');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (693,'Fatty acids, total trans-monoenoic','g',NULL,1,'FATRNM');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (695,'Fatty acids, total trans-polyenoic','g',NULL,1,'FATRNP');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (696,'13:0','g',NULL,1,'F13D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (697,'15:1','g',NULL,1,'F15D1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (851,'18:3 n-3 c,c,c (ALA)','g',NULL,1,'F18D3CN3');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (852,'20:3 n-3','g',NULL,1,'F20D3N3');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (853,'20:3 n-6','g',NULL,1,'F20D3N6');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (855,'20:4 n-6','g',NULL,1,'F20D4N6');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (856,'18:3i','g',NULL,1,'');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (857,'21:5','g',NULL,1,'F21D5');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (858,'22:4','g',NULL,1,'F22D4');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (859,'18:1-11t (18:1t n-7)','g',NULL,1,'F18D1TN7');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (860,'Viscosity','Pa*s','',0,'µ');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (861,'Water Activity','Fraction','Water Activity',0,'a_w');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (863,'Mass Diffusivity','m^2/s','diffusion coefficient',0,'D');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (864,'Temperature in Kelvin','K','Temperature in Kelvin',1,'Tk');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (865,'Initial Freezing Point','C','Temperature at which a material first begins to freeze',0,'T_fi');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (866,'Enthalpy','J','thermodynamic potential energy',0,'H');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (868,'test','min','Rate Constant ',1,'');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (875,'Monosaccharide','frac','',0,'MONOSACC');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (876,'Disaccharide','frac','',0,'DISACC');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (877,'Mineral','frac','',0,'MINRL_FRAC');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (878,'Total Solute Molality','mol/g','',0,'');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (879,'Acid Base','frac','',0,'');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (880,'Sum of Solids','frac','',0,'xs');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (881,'Bound Water Fraction','frac','',0,'xb');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (882,'Product Specific Constant for Bound Water Frac','dimensionless','',0,'c_bw');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (883,'Concentration of Solids','%','% of solids',1,'solid');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (884,'Flow Consistency Index (Power Eqn)','Pa*s^n','',0,'K_flow');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (885,'Flow Behavior Index (Power Eqn)','dimensionless','',0,'n');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (886,'Activation Energy Ea','kJ/mol','energy',1,'Ea');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (887,'Arrhenius Constant','min^-1','Frequency factor',0,'Ar');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (888,'Kinetic Rate Constant k','min^-1','',0,'k_kinetic');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (889,'Concentration','°Brix','Brix measurement of Semisolid foods',1,'Conc_Brix');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (891,'Tortuosity','frac','arc/chord ratio',1,'Tor');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (892,'Vapor Pressure','Pa','Pressure exerted by vapor',1,'VPa');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (893,'Molecular Diffusivity','m^2/s','diffusivity of gas a through gas b, occupying pores in the solid',1,'Dab');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (894,'Solid Pressure','Pascal','Pressure of solid material',1,'Ps');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (895,'Total Pressure','Pascal','Overall pressure',1,'Pt');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (896,'Water pressure','Pascal','pressure exerted by water',1,'Pw');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (897,'derivative of water activity with respect to moisture content','dimensionless','change in water activity as moisture content changes',1,'dadx');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (898,'Density, Bulk','kg/m^3','mass divided by total bulk volume, which includes particle volume, inter-particle void volume, and internal pore volume',1,'ρ_B');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (899,'Chlorine, Cl','mg','',1,'Cl');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (900,'Nitrates','mg','',1,'Nitrate');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (901,'Oxalic Acid','mg','',1,'OxAcid');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (902,'Lactic Acid','mg','',1,'LacAcid');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (903,'Malic Acid','mg','',1,'MalAcid');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (904,'Citric Acid','mg','',1,'CitAcid');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (905,'Fiber fraction','frac','Fraction of fiber',1,'Fib');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (906,'Reference moisture diffusivity of Dry Phase (X=0 T=60 C)','m^2/s','moisture diffusivity associated with the dry phase of the food',0,'D0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (907,'Reference moisture diffusivity of Wet Phase (X=inf T=60)','m^2/s','moisture diffusivity associated with the wet phase of the food',1,'D1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (908,'moisture content','kg/kg','fraction of water mass to solid mass',1,'X');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (909,'z value','K','z value at T1',1,'z_T1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (910,'D value at Reference Time','min','D value at T1',1,'D_T1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (911,'Activation energy of dry material X=0','joules/mol','activation energy needed to diffuse in dry material',1,'E0');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (912,'Activation energy of wet material X=inf','joules/mol','activation energy needed to diffuse in wet material',1,'E1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (913,'Ash fraction','frac','Fraction of ash',1,'Fash');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (914,'k Reference','min^-1','Experimentally Obtained value of k at a specific temperature',1,'k_T1');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (915,'Reference Temperature in Kelvin','K','Temperature T1',1,'T1_k');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (916,'Emulsifier','%','',1,'x_em');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (917,'Specific Enthalpy','kJ/kg','',0,'h_spec');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (918,'Specific Heat Above Freezing','kJ/(kg*K)','',0,'c_unfrozen');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (919,'Specific Heat Below Freezing','kJ/(kg*K)','',0,'c_frozen');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (920,'Pressure','atm','',1,'P_atm');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (921,'Moisture Ratio','unitless','',1,'MR');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (922,'Decimal Reduction Time','min','D value',0,'D_val');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (923,'Water Content','kg/kg dry solids','Amount of water adsorbed (kg/kg dry solids)',0,'u');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (924,'Reference Temperature in Celsius ','C','',1,'T1_C');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (925,'xproperty','xp','xp Test',1,'xp');
INSERT INTO `variables` (`id`,`Name`,`SIUnit`,`Description`,`is_factor`,`Symbol`) VALUES (926,'xvariable','xv','xv Test',0,'xv');
